// src/lib/components/LocalProjectList.svelte
<script>
	import { resolve } from '$app/paths';
	import { ImagePlus, Trash2 } from 'lucide-svelte';
	import ProjectThumb from './ProjectThumb.svelte';
	import Modal from './Modal.svelte';
	import { shellHref } from '$lib/app/navigation';
	import { getCloudWorkspace } from '$lib/cloud/workspace.svelte';
	import { removeProject } from '$lib/editor/removeProject';

	/**
	 * @type {{
	 *   repository: import('$lib/persistence/repository').StickerLabRepository,
	 *   emptyTitle?: string,
	 *   emptyDetail?: string,
	 *   limit?: number,
	 *   refreshToken?: number,
	 * }}
	 */
	let {
		repository,
		emptyTitle = 'No projects yet',
		emptyDetail = 'Your local projects will appear here.',
		limit = undefined,
		refreshToken = 0
	} = $props();

	/** @type {import('$lib/domain/domain').ProjectDocument[] | null} */
	let projects = $state(null);
	/** @type {import('$lib/domain/domain').ProjectDocument | null} */
	let pending = $state(null);
	let busy = $state(false);
	let error = $state(/** @type {string | null} */ (null));
	let opener = $state(/** @type {HTMLButtonElement | undefined} */ (undefined));

	/** @type {import('$lib/domain/domain').ProjectDocument[]} */
	let visible = $derived(limit ? (projects ?? []).slice(0, limit) : (projects ?? []));

	const workspace = getCloudWorkspace();
	const cloud = $derived(workspace.cloud !== null);

	function reload() {
		return repository
			.listProjects()
			.then((list) => (projects = list))
			.catch(() => (projects = []));
	}

	$effect(() => {
		// Re-read whenever the repository, an explicit refresh token or a cloud
		// status update (another device, a retry, a conflict copy) changes.
		void repository;
		void refreshToken;
		void workspace.cloudStatus.version;
		let live = true;
		repository
			.listProjects()
			.then((list) => {
				if (live) projects = list;
			})
			.catch(() => {
				if (live) projects = [];
			});
		return () => {
			live = false;
		};
	});
</script>

{#if projects === null}
	<p class="muted">Loading projects…</p>
{:else if visible.length === 0}
	<div class="project-empty">
		<ImagePlus size={28} />
		<b>{emptyTitle}</b>
		<span>{emptyDetail}</span>
		<a href={shellHref('/create')}>Create your first sticker</a>
	</div>
{:else}
	<div class="project-grid">
		{#each visible as project (project.id)}
			<article class="project-card">
				<a class="project-card-link" href={resolve(`/editor/${project.id}`)}>
					<ProjectThumb {project} {repository} />
					<b>{project.title}</b>
					<small>{cloud ? 'Private workspace' : 'Saved locally'}</small>
				</a>
				<button
					type="button"
					class="button icon project-delete"
					aria-label={`Delete ${project.title}`}
					onclick={(event) => {
						opener = event.currentTarget;
						error = null;
						pending = project;
					}}
				>
					<Trash2 size={16} />
				</button>
			</article>
		{/each}
		<a class="project-card project-new" href={shellHref('/create')}>
			<div class="project-thumb">+</div>
			<b>New project</b>
			<small>Start creating</small>
		</a>
	</div>
{/if}

<Modal
	open={pending !== null}
	title="Delete this sticker?"
	description={`“${pending?.title ?? ''}” will be removed from this browser. Any pack memberships for this sticker will be removed; the other stickers in those packs will be kept.`}
	onclose={() => {
		pending = null;
		opener?.focus();
	}}
	focusOnOpen={() => document.querySelector('#cancel-delete-project')}
>
	{#if error}
		<p role="alert">{error}</p>
	{/if}
	{#snippet footer()}
		<button
			type="button"
			id="cancel-delete-project"
			class="button"
			onclick={() => {
				pending = null;
				opener?.focus();
			}}>Keep sticker</button
		>
		<button
			type="button"
			class="button danger"
			disabled={busy}
			onclick={async () => {
				if (!pending) return;
				busy = true;
				error = null;
				try {
					await removeProject(repository, pending);
					pending = null;
					await reload();
				} catch (cause) {
					error =
						cause instanceof Error ? cause.message : 'Could not delete this sticker. Please retry.';
				} finally {
					busy = false;
				}
			}}>Delete sticker</button
		>
	{/snippet}
</Modal>

// src/features/editor/LocalProjectList.tsx
import { useEffect, useRef, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { ImagePlus, Trash2 } from 'lucide-react'
import { useRepository } from '../../app/repository'
import { useCloudStatus, useWorkspace } from '../auth/Workspace'
import type { ProjectDocument } from '../../types/domain'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogTitle } from '@/components/ui/dialog'
import { ProjectThumb } from './ProjectThumb'
import { removeProject } from './removeProject'

export function LocalProjectList({
  emptyTitle = 'No projects yet',
  emptyDetail = 'Your local projects will appear here.',
  limit,
}: {
  emptyTitle?: string
  emptyDetail?: string
  limit?: number
}) {
  const repo = useRepository()
  const cloud = useWorkspace()?.cloud
  const cloudStatus = useCloudStatus()
  const location = useLocation()
  const [projects, setProjects] = useState<ProjectDocument[] | null>(null)
  const [pending, setPending] = useState<ProjectDocument | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const opener = useRef<HTMLButtonElement | null>(null)

  const reload = () => repo.listProjects().then(setProjects).catch(() => setProjects([]))

  useEffect(() => {
    let live = true
    repo.listProjects().then((list) => { if (live) setProjects(list) }).catch(() => { if (live) setProjects([]) })
    return () => { live = false }
  }, [repo, location.pathname, location.key, cloudStatus.version])

  if (!projects) return <p className="muted">Loading projects…</p>
  const visible = limit ? projects.slice(0, limit) : projects
  if (visible.length === 0) {
    return (
      <div className="project-empty">
        <ImagePlus size={28} />
        <b>{emptyTitle}</b>
        <span>{emptyDetail}</span>
        <Link to="/create">Create your first sticker</Link>
      </div>
    )
  }

  return (
    <>
      <div className="project-grid">
        {visible.map((project) => (
          <article className="project-card" key={project.id}>
            <Link className="project-card-link" to={`/editor/${project.id}`}>
              <ProjectThumb project={project} repo={repo} />
              <b>{project.title}</b>
              <small>{cloud ? 'Private workspace' : 'Saved locally'}</small>
            </Link>
            <Button
              className="icon project-delete"
              aria-label={`Delete ${project.title}`}
              onClick={(event) => { opener.current = event.currentTarget; setError(null); setPending(project) }}
            >
              <Trash2 size={16} />
            </Button>
          </article>
        ))}
        <Link className="project-card project-new" to="/create">
          <div className="project-thumb">+</div>
          <b>New project</b>
          <small>Start creating</small>
        </Link>
      </div>
      <Dialog open={pending !== null} onOpenChange={(open) => { if (!open) setPending(null) }}>
        <DialogContent
          onOpenAutoFocus={(event) => { event.preventDefault(); document.getElementById('cancel-delete-project')?.focus() }}
          onCloseAutoFocus={(event) => { event.preventDefault(); opener.current?.focus() }}
        >
          <DialogTitle>Delete this sticker?</DialogTitle>
          <DialogDescription>
            “{pending?.title}” will be removed {cloud ? 'from your private StickerLab account on this device and other signed-in devices' : 'from this browser'}.
            Any pack memberships for this sticker will be removed; the other stickers in those packs will be kept.
          </DialogDescription>
          {error ? <p role="alert">{error}</p> : null}
          <DialogFooter>
            <Button id="cancel-delete-project" onClick={() => setPending(null)}>Keep sticker</Button>
            <Button
              className="danger"
              disabled={busy}
              onClick={() => {
                if (!pending) return
                setBusy(true)
                setError(null)
                void removeProject(repo, pending).then(() => {
                  setPending(null)
                  return reload()
                }).catch((cause) => {
                  setError(cause instanceof Error ? cause.message : 'Could not delete this sticker. Please retry.')
                }).finally(() => setBusy(false))
              }}
            >
              Delete sticker
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  )
}
