// src/features/presentations/editor/StickerPickerDialog.tsx
/**
 * Saved-sticker picker for the presentation editor (P33). Lists the real local
 * sticker projects; choosing one asks the page to snapshot and place it. An
 * empty or unreadable library says so instead of rendering dead controls.
 */

import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import type { StickerLabRepository } from '@/lib/persistence/repository'
import type { ProjectDocument } from '@/types/domain'

export function StickerPickerDialog({ repository, disabled, onPick }: { repository: StickerLabRepository; disabled?: boolean; onPick: (projectId: string) => void }) {
  const [open, setOpen] = useState(false)
  const [projects, setProjects] = useState<ProjectDocument[] | null>(null)
  const [error, setError] = useState(false)

  useEffect(() => {
    if (!open) return
    let live = true
    setProjects(null)
    setError(false)
    repository.listProjects()
      .then((list) => {
        if (live) setProjects([...list].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)))
      })
      .catch(() => {
        if (live) setError(true)
      })
    return () => { live = false }
  }, [open, repository])

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button disabled={disabled}>Add sticker</Button>
      </DialogTrigger>
      <DialogContent>
        <DialogTitle>Add a saved sticker</DialogTitle>
        <DialogDescription>A snapshot is placed as its own image. Editing or deleting the sticker later does not change it.</DialogDescription>
        {error ? <p role="alert">Your saved stickers could not be read.</p> : null}
        {projects === null && !error ? <p role="status">Loading stickers…</p> : null}
        {projects?.length === 0 ? <p>No saved stickers yet. Create one in the sticker editor first.</p> : null}
        <ul className="presentation-sticker-picker">
          {projects?.map((project) => (
            <li key={project.id}>
              <Button
                onClick={() => {
                  onPick(project.id)
                  setOpen(false)
                }}
              >
                {project.title || 'Untitled sticker'}
                <span>{project.layers.length} {project.layers.length === 1 ? 'layer' : 'layers'}</span>
              </Button>
            </li>
          ))}
        </ul>
      </DialogContent>
    </Dialog>
  )
}

// src/lib/components/presentation/StickerPickerDialog.svelte
<script>
	import Modal from '$lib/components/Modal.svelte';

	/**
	 * Saved-sticker picker for the presentation editor (P33). Lists the real local
	 * sticker projects; choosing one asks the page to snapshot and place it. An
	 * empty or unreadable library says so instead of rendering dead controls.
	 *
	 * @type {{
	 *   repository: import('$lib/persistence/repository').StickerLabRepository,
	 *   disabled?: boolean,
	 *   onpick: (projectId: string) => void
	 * }}
	 */
	let { repository, disabled = false, onpick } = $props();

	let open = $state(false);
	/** @type {import('$lib/domain/domain').ProjectDocument[] | null} */
	let projects = $state.raw(null);
	let error = $state(false);
	/** @type {HTMLButtonElement | null} */
	let opener = null;

	$effect(() => {
		if (!open) return;
		let live = true;
		projects = null;
		error = false;
		repository
			.listProjects()
			.then((list) => {
				if (live) projects = [...list].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
			})
			.catch(() => {
				if (live) error = true;
			});
		return () => {
			live = false;
		};
	});
</script>

<button type="button" class="button" bind:this={opener} {disabled} onclick={() => (open = true)}
	>Add sticker</button
>
<Modal
	{open}
	title="Add a saved sticker"
	description="A snapshot is placed as its own image. Editing or deleting the sticker later does not change it."
	onclose={() => (open = false)}
	onclosed={() => opener?.focus()}
>
	{#if error}<p role="alert">Your saved stickers could not be read.</p>{/if}
	{#if projects === null && !error}<p role="status">Loading stickers…</p>{/if}
	{#if projects?.length === 0}<p>
			No saved stickers yet. Create one in the sticker editor first.
		</p>{/if}
	<ul class="presentation-sticker-picker">
		{#each projects ?? [] as project (project.id)}
			<li>
				<button
					type="button"
					class="button"
					onclick={() => {
						onpick(project.id);
						open = false;
					}}
				>
					{project.title || 'Untitled sticker'}
					<span>{project.layers.length} {project.layers.length === 1 ? 'layer' : 'layers'}</span>
				</button>
			</li>
		{/each}
	</ul>
</Modal>
