// src/lib/components/presentation/PresentationCanvasControls.svelte
<script>
	import { Minus, Plus, Scan } from 'lucide-svelte';
	import {
		clampPresentationZoom,
		PRESENTATION_MAX_ZOOM,
		PRESENTATION_MIN_ZOOM
	} from '$lib/presentations/editor/viewGeometry';

	/** @type {{ store: import('$lib/presentations/editor/store.svelte').PresentationStore }} */
	let { store } = $props();
	let zoom = $derived(store.current.view.zoom);

	/** @param {number} factor */
	function zoomBy(factor) {
		const current = store.getState().view.zoom;
		store.getState().setZoom(clampPresentationZoom(current * factor));
	}

	function fit() {
		store.getState().setZoom(1);
		store.getState().setPan({ x: 0, y: 0 });
	}
</script>

<div class="presentation-canvas-controls" aria-label="Canvas view controls">
	<button
		class="button icon"
		aria-label="Zoom out"
		onclick={() => zoomBy(0.8)}
		disabled={zoom <= PRESENTATION_MIN_ZOOM}><Minus size={17} /></button
	>
	<output aria-label="Canvas zoom">{Math.round(zoom * 100)}%</output>
	<button
		class="button icon"
		aria-label="Zoom in"
		onclick={() => zoomBy(1.25)}
		disabled={zoom >= PRESENTATION_MAX_ZOOM}><Plus size={17} /></button
	>
	<button class="button icon" aria-label="Fit slide to window" onclick={fit}
		><Scan size={17} /></button
	>
</div>

// src/features/presentations/editor/PresentationCanvasControls.tsx
import { Minus, Plus, Scan } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { usePresentationStore } from './store'
import { clampPresentationZoom, PRESENTATION_MAX_ZOOM, PRESENTATION_MIN_ZOOM } from './viewGeometry'

/**
 * Shared canvas view controls. Both the Konva canvas and the test-mode host
 * render this component so zoom limits, labels, and fit behaviour are identical
 * everywhere.
 */
export function PresentationCanvasControls() {
  const zoom = usePresentationStore((state) => state.view.zoom)

  const zoomBy = (factor: number) => {
    usePresentationStore.getState().setZoom(clampPresentationZoom(usePresentationStore.getState().view.zoom * factor))
  }
  const fit = () => {
    usePresentationStore.getState().setZoom(1)
    usePresentationStore.getState().setPan({ x: 0, y: 0 })
  }

  return (
    <div className="presentation-canvas-controls" aria-label="Canvas view controls">
      <Button className="icon" aria-label="Zoom out" onClick={() => zoomBy(0.8)} disabled={zoom <= PRESENTATION_MIN_ZOOM}><Minus size={17} /></Button>
      <output aria-label="Canvas zoom">{Math.round(zoom * 100)}%</output>
      <Button className="icon" aria-label="Zoom in" onClick={() => zoomBy(1.25)} disabled={zoom >= PRESENTATION_MAX_ZOOM}><Plus size={17} /></Button>
      <Button className="icon" aria-label="Fit slide to window" onClick={fit}><Scan size={17} /></Button>
    </div>
  )
}
