// src/lib/components/presentation/PresentationCanvas.svelte
<script>
	import { Konva } from '$lib/presentations/rendering/konvaText';
	import { renderSlide } from '$lib/presentations/rendering/renderSlide';
	import {
		clampPresentationZoom,
		presentationViewport
	} from '$lib/presentations/editor/viewGeometry';
	import { snapToAlignment } from '$lib/presentations/editor/alignmentGuides';
	import {
		documentPointFromView,
		elementGeometry,
		elementWorldCenter,
		moveTransform,
		nextRotationStep,
		resizeTransform,
		rotateTransform,
		rotationFromPoint
	} from '$lib/presentations/editor/transformGeometry';
	import PresentationCanvasControls from './PresentationCanvasControls.svelte';
	import PresentationSelectionFrame from './PresentationSelectionFrame.svelte';
	import TextEditOverlay from './TextEditOverlay.svelte';

	/**
	 * @typedef {import('$lib/presentations/editor/transformGeometry').TransformGeometry} TransformGeometry
	 * @typedef {import('$lib/presentations/editor/transformGeometry').ViewPoint} ViewPoint
	 * @typedef {import('$lib/presentations/editor/transformGeometry').ResizeHandle} ResizeHandle
	 * @typedef {import('$lib/presentations/editor/alignmentGuides').AlignmentGuide} AlignmentGuide
	 * @typedef {import('$lib/presentations/model/types').Element} Element
	 *
	 * @typedef {{
	 *   pointerId: number,
	 *   x: number,
	 *   y: number,
	 *   capture: HTMLElement | null
	 * }} PanGesture
	 *
	 * @typedef {{
	 *   kind: 'move' | 'resize' | 'rotate',
	 *   pointerId: number,
	 *   elementId: string,
	 *   handle: ResizeHandle | null,
	 *   origin: ViewPoint,
	 *   start: TransformGeometry,
	 *   current: TransformGeometry | null,
	 *   pointerAngle: number,
	 *   rotationTurn: number,
	 *   capture: HTMLElement | null
	 * }} TransformGesture
	 */

	/** @type {{
	 *   store: import('$lib/presentations/editor/store.svelte').PresentationStore,
	 *   images: import('$lib/presentations/rendering/renderSlide').PresentationImageSources,
	 *   session: import('$lib/presentations/editor/textEditSession.svelte').TextEditSession
	 * }} */
	let { store, images, session } = $props();

	/** @type {HTMLDivElement | null} */
	let hostEl = null;
	/** @type {Konva.Stage | null} */
	let stage = null;
	/** @type {Konva.Layer | null} */
	let layer = null;
	/** @type {PanGesture | null} */
	let panGesture = null;
	/** @type {TransformGesture | null} */
	let transformGesture = null;
	/** The group a live preview was applied to, so it can be put back on cancel. @type {string | null} */
	let previewedNodeId = null;
	let wasEditing = false;
	/** Set while the click that ends a transform gesture is still on its way. */
	let ignoreTrailingClick = false;

	let ready = $state(false);
	let size = $state.raw({ width: 0, height: 0 });
	let renderError = $state(false);
	let panning = $state(false);

	const editorState = $derived(store.current);
	const presentation = $derived(editorState.document);
	const activeSlide = $derived(
		presentation?.slides.find((slide) => slide.id === editorState.view.activeSlideId) ??
			presentation?.slides[0]
	);
	const selectedElementId = $derived(editorState.view.selectedElementIds[0] ?? null);
	const selectedElement = $derived(
		activeSlide?.elements.find((element) => element.id === selectedElementId)
	);
	const editingElementId = $derived(editorState.view.editingElementId);
	const editingElement = $derived(
		activeSlide?.elements.find((element) => element.id === editingElementId)
	);
	// The two view numbers are read through their own deriveds: a selection change
	// replaces the store object, and an effect reading `editorState` directly would
	// re-render the layer for it, destroying the hit graph mid-click.
	const viewZoom = $derived(editorState.view.zoom);
	const viewPan = $derived(editorState.view.pan);
	const viewport = $derived(
		presentationViewport(
			size,
			presentation?.pageSize ?? { width: 0, height: 0 },
			editorState.view.zoom,
			editorState.view.pan
		)
	);
	// While a gesture runs, the frame and its handles describe the previewed
	// geometry; the document only changes when the gesture is committed.
	const selectedGeometry = $derived(
		selectedElement
			? elementGeometry(selectedElement, editorState.view.transformPreview ?? null)
			: null
	);

	// The stage's size, scale and position follow the viewport alone, so panning and
	// zooming never rebuild the painted children.
	$effect(() => {
		const konvaStage = stage;
		const doc = presentation;
		const canvasSize = size;
		const zoom = viewZoom;
		const pan = viewPan;
		if (!konvaStage || !doc) return;
		const currentViewport = presentationViewport(canvasSize, doc.pageSize, zoom, pan);
		konvaStage.size({
			width: Math.max(1, canvasSize.width),
			height: Math.max(1, canvasSize.height)
		});
		konvaStage.scale({ x: currentViewport.scale, y: currentViewport.scale });
		konvaStage.position({ x: currentViewport.x, y: currentViewport.y });
		konvaStage.batchDraw();
	});

	// The painted slide is rebuilt only when the document, the visible slide, the
	// decoded images or the edited element change. The source's React effect had
	// the same dependency list, and keeping it that narrow is what lets a click
	// that follows a selection still hit the element it pressed.
	$effect(() => {
		const konvaLayer = layer;
		const doc = presentation;
		const slide = activeSlide;
		const editingId = editingElementId;
		// The stage and its layer belong to the attachment; `ready` flips with them,
		// so reading it repaints as soon as the canvas exists.
		const mounted = ready;
		if (!mounted || !konvaLayer || !doc || !slide) return;
		konvaLayer.destroyChildren();
		try {
			const page = renderSlide({ slide, pageSize: doc.pageSize, images, listening: true });
			if (editingId) {
				// The DOM overlay draws the text being edited; hide the canvas copy.
				for (const child of page.getChildren()) {
					if (child.id() === editingId) {
						child.visible(false);
						break;
					}
				}
			}
			konvaLayer.add(page);
			renderError = false;
		} catch {
			// A missing decoded asset must not unmount the whole editor: the
			// preview reports the problem and the rest keeps working.
			renderError = true;
		}
		konvaLayer.batchDraw();
	});

	// Live gesture feedback on the rendering layer only: the group follows the
	// pointer, and the committed document redraws it at its real geometry. A
	// cancelled gesture puts the node back where the document says it is.
	$effect(() => {
		const konvaLayer = layer;
		const preview = editorState.view.transformPreview;
		const id = preview?.elementId ?? previewedNodeId;
		if (!konvaLayer || !id) return;
		const element = activeSlide?.elements.find((candidate) => candidate.id === id);
		const node = /** @type {Konva.Group | undefined} */ (konvaLayer.findOne(`#${id}`));
		if (element && node) {
			const geometry = elementGeometry(element, preview ?? null);
			node.setAttrs({
				x: geometry.x,
				y: geometry.y,
				rotation: geometry.rotation,
				// Preview only: the group is scaled so the drag tracks the pointer. The
				// stored element keeps its own size and is re-rendered from it.
				scaleX: geometry.width / element.width,
				scaleY: geometry.height / element.height
			});
			konvaLayer.batchDraw();
		}
		previewedNodeId = preview?.elementId ?? null;
	});

	// Keep focus in the editor when the text overlay closes, but never steal it.
	$effect(() => {
		const editingId = editorState.view.editingElementId;
		if (editingId) {
			wasEditing = true;
			return;
		}
		if (!wasEditing || !hostEl) return;
		wasEditing = false;
		const active = window.document.activeElement;
		if (active === null || active === window.document.body) hostEl.focus();
	});

	/**
	 * One pointer position in document units, through the shared viewport mapping.
	 * @param {number} clientX
	 * @param {number} clientY
	 */
	function pointFromClient(clientX, clientY) {
		if (!hostEl) return null;
		const rect = hostEl.getBoundingClientRect();
		const current = store.getState();
		const pageSize = current.document?.pageSize ?? { width: 0, height: 0 };
		const currentViewport = presentationViewport(
			size,
			pageSize,
			current.view.zoom,
			current.view.pan
		);
		return documentPointFromView(
			{ x: clientX - rect.left, y: clientY - rect.top },
			currentViewport
		);
	}

	/**
	 * The visible element under the pointer, or null over the slide background.
	 * @param {number} clientX
	 * @param {number} clientY
	 */
	function elementAtPointer(clientX, clientY) {
		const current = store.getState();
		const slide =
			current.document?.slides.find((item) => item.id === current.view.activeSlideId) ??
			current.document?.slides[0];
		if (!stage || !hostEl || !slide) return null;
		const rect = hostEl.getBoundingClientRect();
		const hit = stage.getIntersection({ x: clientX - rect.left, y: clientY - rect.top });
		if (!hit) return null;
		const group = /** @type {Konva.Group | undefined} */ (
			hit.findAncestor('.presentation-element', true)
		);
		const id = group?.id();
		return id ? (slide.elements.find((element) => element.id === id) ?? null) : null;
	}

	/** @returns {HTMLElement | null} */
	function captureTarget() {
		return /** @type {HTMLElement | null} */ (hostEl?.querySelector('.konvajs-content') ?? hostEl);
	}

	/**
	 * @param {Element} element
	 * @param {TransformGesture['kind']} kind
	 * @param {ResizeHandle | null} handle
	 * @param {PointerEvent} event
	 */
	function beginTransform(element, kind, handle, event) {
		const origin = pointFromClient(event.clientX, event.clientY);
		if (!origin) return;
		const start = elementGeometry(element, null);
		// Capture on the Konva container for every transform gesture, so move/up
		// arrive through the same host handlers as panning.
		const capture = captureTarget();
		transformGesture = {
			kind,
			pointerId: event.pointerId,
			elementId: element.id,
			handle,
			origin,
			start,
			current: null,
			// Rotation measures the pointer angle around the element's visual centre.
			pointerAngle: kind === 'rotate' ? rotationFromPoint(elementWorldCenter(start), origin) : 0,
			rotationTurn: 0,
			capture
		};
		try {
			capture?.setPointerCapture(event.pointerId);
		} catch {
			// Window-level pointer events still reach the host.
		}
	}

	/**
	 * The candidate geometry for one pointer position. Move and resize measure
	 * from the gesture's start; rotation walks the pointer angle step by step,
	 * updating the gesture, so a continuous turn accumulates instead of jumping at
	 * the ±180° branch cut.
	 *
	 * @param {TransformGesture} gesture
	 * @param {ViewPoint} point
	 */
	function previewGeometry(gesture, point) {
		if (gesture.kind === 'move')
			return moveTransform(gesture.start, {
				x: point.x - gesture.origin.x,
				y: point.y - gesture.origin.y
			});
		if (gesture.kind === 'resize')
			return resizeTransform(gesture.start, /** @type {ResizeHandle} */ (gesture.handle), point);
		const step = nextRotationStep(
			gesture.pointerAngle,
			rotationFromPoint(elementWorldCenter(gesture.start), point),
			gesture.rotationTurn
		);
		gesture.pointerAngle = step.angle;
		gesture.rotationTurn = step.accumulated;
		return rotateTransform(gesture.start, step.accumulated);
	}

	/**
	 * Applies pointer movement to the live gesture; returns whether one is running.
	 * @param {PointerEvent} event
	 */
	function applyGestureMove(event) {
		const gesture = transformGesture;
		if (!gesture || gesture.pointerId !== event.pointerId) return false;
		// A mouse drag whose button was released outside the window must not keep
		// transforming on plain hover movement.
		if (event.pointerType === 'mouse' && (event.buttons & 1) === 0) {
			endTransform(event.pointerId, false);
			return true;
		}
		const point = pointFromClient(event.clientX, event.clientY);
		if (!point) return true;
		let current = previewGeometry(gesture, point);
		/** @type {AlignmentGuide[]} */
		let nextGuides = [];
		// Move gestures snap to other visible elements and the page axes, and show
		// the matched lines. Resize and rotate keep exact pointer geometry.
		const state = store.getState();
		const slide =
			state.document?.slides.find((item) => item.id === state.view.activeSlideId) ??
			state.document?.slides[0];
		if (gesture.kind === 'move' && slide && state.document) {
			const others = slide.elements
				.filter((element) => element.id !== gesture.elementId && element.visible)
				.map((element) => elementGeometry(element, null));
			const snapped = snapToAlignment(current, others, state.document.pageSize);
			current = { ...current, x: snapped.x, y: snapped.y };
			nextGuides = snapped.guides;
		}
		gesture.current = current;
		state.setTransformPreview({ elementId: gesture.elementId, ...current });
		state.setGuides(nextGuides);
		return true;
	}

	/**
	 * Drops the compatibility click that closes this pointer gesture. Konva
	 * reports its click from the `mouseup`/`touchend` event, which the browser
	 * dispatches after this component's `pointerup`; by then the layer may be
	 * mid-repaint, so the click's hit test can answer "the background" and clear
	 * the selection the pointerdown just made. The pointerdown already selected
	 * the element, so the trailing click is the end of a gesture, not a click on
	 * empty canvas.
	 */
	function dropTrailingClick() {
		ignoreTrailingClick = true;
		setTimeout(() => (ignoreTrailingClick = false), 0);
	}

	/** @param {number} pointerId @param {boolean} commit */
	function endTransform(pointerId, commit) {
		const gesture = transformGesture;
		if (gesture?.pointerId !== pointerId) return;
		transformGesture = null;
		dropTrailingClick();
		if (gesture.capture?.hasPointerCapture(pointerId)) {
			try {
				gesture.capture.releasePointerCapture(pointerId);
			} catch {
				// Pointer capture already ended.
			}
		}
		const state = store.getState();
		// A click without movement leaves no undo entry and no revision behind.
		if (commit && gesture.current) state.commitTransform(gesture.elementId, gesture.current);
		else if (gesture.current) state.setTransformPreview(null);
		state.setGuides([]);
	}

	/** @param {number} pointerId */
	function endPan(pointerId) {
		const gesture = panGesture;
		if (gesture?.pointerId !== pointerId) return;
		panGesture = null;
		panning = false;
		if (gesture.capture?.hasPointerCapture(pointerId)) {
			try {
				gesture.capture.releasePointerCapture(pointerId);
			} catch {
				// Pointer capture already ended.
			}
		}
	}

	/** @param {PointerEvent} event */
	function handlePointerDown(event) {
		if (event.button !== 0) return;
		const element = elementAtPointer(event.clientX, event.clientY);
		if (element) {
			store.getState().selectElements([element.id]);
			// A locked element stays selectable so its properties are reachable,
			// but no gesture may move, resize, or rotate it.
			if (!element.locked) beginTransform(element, 'move', null, event);
			return;
		}
		// Capture on the Konva container so Konva still sees pointerdown/up and can
		// report click/dblclick for element selection.
		const capture = captureTarget();
		panGesture = { pointerId: event.pointerId, x: event.clientX, y: event.clientY, capture };
		panning = true;
		try {
			capture?.setPointerCapture(event.pointerId);
		} catch {
			// Window-level pointer events still update the view.
		}
	}

	/** @param {PointerEvent} event */
	function handlePointerMove(event) {
		if (applyGestureMove(event)) return;
		const gesture = panGesture;
		if (!gesture || gesture.pointerId !== event.pointerId) return;
		// A mouse drag whose button was released outside the window must not keep
		// panning on plain hover movement.
		if (event.pointerType === 'mouse' && (event.buttons & 1) === 0) {
			endPan(event.pointerId);
			return;
		}
		const dx = event.clientX - gesture.x;
		const dy = event.clientY - gesture.y;
		gesture.x = event.clientX;
		gesture.y = event.clientY;
		const state = store.getState();
		state.setPan({ x: state.view.pan.x + dx, y: state.view.pan.y + dy });
	}

	/** @param {WheelEvent} event */
	function handleWheel(event) {
		if (event.deltaY === 0) return;
		event.preventDefault();
		const current = store.getState().view.zoom;
		store.getState().setZoom(clampPresentationZoom(current * (event.deltaY < 0 ? 1.1 : 0.9)));
	}

	/** @type {import('svelte/attachments').Attachment<HTMLDivElement>} */
	const mountCanvas = (node) => {
		hostEl = node;
		const konvaStage = new Konva.Stage({
			container: node,
			width: Math.max(1, node.clientWidth),
			height: Math.max(1, node.clientHeight)
		});
		const konvaLayer = new Konva.Layer();
		konvaStage.add(konvaLayer);
		stage = konvaStage;
		layer = konvaLayer;
		ready = true;

		const resize = () => {
			size = { width: node.clientWidth, height: node.clientHeight };
		};
		resize();
		const observer = new ResizeObserver(resize);
		observer.observe(node);

		const elementIdFor = (/** @type {Konva.Node} */ target) => {
			if (target === konvaStage) return null;
			return (
				/** @type {Konva.Group | undefined} */ (
					target.findAncestor('.presentation-element', true)
				)?.id() || null
			);
		};
		const select = (/** @type {any} */ event) => {
			// A click that only ends a transform gesture is not a click on the
			// background: see `ignoreTrailingClick`.
			if (ignoreTrailingClick) return;
			const id = elementIdFor(event.target);
			store.getState().selectElements(id ? [id] : []);
		};
		const edit = (/** @type {any} */ event) => {
			const id = elementIdFor(event.target);
			if (id) store.getState().startTextEdit(id);
		};
		konvaStage.on('click tap', select);
		konvaStage.on('dblclick dbltap', edit);

		node.addEventListener('wheel', handleWheel, { passive: false });
		node.addEventListener('pointerdown', handlePointerDown);
		node.addEventListener('pointermove', handlePointerMove);
		node.addEventListener('pointerup', handlePointerUp);
		node.addEventListener('pointercancel', handlePointerCancel);

		return () => {
			observer.disconnect();
			node.removeEventListener('wheel', handleWheel);
			node.removeEventListener('pointerdown', handlePointerDown);
			node.removeEventListener('pointermove', handlePointerMove);
			node.removeEventListener('pointerup', handlePointerUp);
			node.removeEventListener('pointercancel', handlePointerCancel);
			konvaStage.destroy();
			stage = null;
			layer = null;
			hostEl = null;
			ready = false;
		};
	};

	/** @param {PointerEvent} event */
	function handlePointerUp(event) {
		endTransform(event.pointerId, true);
		endPan(event.pointerId);
	}

	/** @param {PointerEvent} event */
	function handlePointerCancel(event) {
		endTransform(event.pointerId, false);
		endPan(event.pointerId);
	}
</script>

{#if presentation && activeSlide}
	<section class="presentation-canvas-panel" aria-label="Slide canvas">
		<PresentationCanvasControls {store} />
		<div
			class="presentation-canvas"
			class:is-panning={panning}
			data-ready={ready}
			data-testid="presentation-canvas"
			data-document-width={presentation.pageSize.width}
			data-document-height={presentation.pageSize.height}
			data-view-zoom={editorState.view.zoom}
			data-view-pan-x={editorState.view.pan.x}
			data-view-pan-y={editorState.view.pan.y}
			data-selected-element={selectedElementId ?? ''}
			data-editing-element={editorState.view.editingElementId ?? ''}
			tabindex="-1"
			{@attach mountCanvas}
		></div>
		{#if selectedElement && selectedGeometry && !editingElement}
			<PresentationSelectionFrame
				geometry={selectedGeometry}
				{viewport}
				locked={selectedElement.locked}
				ongesturestart={(kind, handle, event) => {
					// The handle gesture must not also start a pan or a move on the host.
					event.preventDefault();
					event.stopPropagation();
					beginTransform(selectedElement, kind, handle, event);
				}}
			/>
		{/if}
		{#if editingElement?.kind === 'text'}
			<TextEditOverlay
				element={editingElement}
				scale={viewport.scale}
				offsetX={viewport.x}
				offsetY={viewport.y}
				theme={presentation.theme}
				{session}
				{store}
			/>
		{/if}
		{#if renderError}<p class="presentation-canvas-error" role="alert">
				Some artwork on this slide could not be drawn. Your saved presentation is unchanged.
			</p>{/if}
		{#if activeSlide.elements.length === 0 && !renderError}<p
				class="presentation-blank-slide"
				aria-hidden="true"
			>
				Blank slide
			</p>{/if}
		{#each editorState.view.guides as guide, index (`${guide.axis}-${guide.position}-${index}`)}
			<div
				class="presentation-guide is-{guide.axis}"
				data-testid="presentation-guide-{guide.axis}"
				aria-hidden="true"
				style:left={guide.axis === 'x'
					? `${viewport.x + guide.position * viewport.scale}px`
					: undefined}
				style:top={guide.axis === 'y'
					? `${viewport.y + guide.position * viewport.scale}px`
					: undefined}
				style:height={guide.axis === 'x'
					? `${presentation.pageSize.height * viewport.scale}px`
					: undefined}
				style:width={guide.axis === 'y'
					? `${presentation.pageSize.width * viewport.scale}px`
					: undefined}
			></div>
		{/each}
	</section>
{/if}

// src/features/presentations/editor/PresentationCanvas.tsx
import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { Konva } from '../rendering/konvaText'
import { renderSlide, type PresentationImageSources } from '../rendering/renderSlide'
import { TextEditOverlay } from './TextEditOverlay'
import { usePresentationStore } from './store'
import { PresentationCanvasControls } from './PresentationCanvasControls'
import { PresentationSelectionFrame } from './PresentationSelectionFrame'
import { presentationViewport, clampPresentationZoom } from './viewGeometry'
import { snapToAlignment, type AlignmentGuide } from './alignmentGuides'
import {
  documentPointFromView,
  elementGeometry,
  elementWorldCenter,
  moveTransform,
  nextRotationStep,
  resizeTransform,
  rotateTransform,
  rotationFromPoint,
  type ResizeHandle,
  type TransformGeometry,
  type ViewPoint,
} from './transformGeometry'
import type { Element } from '../model/types'

type CanvasSize = { width: number; height: number }

type PanGesture = { pointerId: number; x: number; y: number; capture: HTMLElement | null }

type TransformGesture = {
  kind: 'move' | 'resize' | 'rotate'
  pointerId: number
  elementId: string
  handle: ResizeHandle | null
  /** Document point where the gesture started. */
  origin: ViewPoint
  /** Element geometry when the gesture started. */
  start: TransformGeometry
  /** Latest previewed geometry; null until the pointer actually moves. */
  current: TransformGeometry | null
  /** Rotating only: pointer angle at the previous move, and the turn so far. */
  pointerAngle: number
  rotationTurn: number
  capture: HTMLElement | null
}

export function PresentationCanvas({ images }: { images: PresentationImageSources }) {
  const hostRef = useRef<HTMLDivElement>(null)
  const stageRef = useRef<Konva.Stage | null>(null)
  const layerRef = useRef<Konva.Layer | null>(null)
  const panGesture = useRef<PanGesture | null>(null)
  const transformGesture = useRef<TransformGesture | null>(null)
  /** The group a live preview was applied to, so it can be put back on cancel. */
  const previewedNodeId = useRef<string | null>(null)
  const wasEditing = useRef(false)
  const [panning, setPanning] = useState(false)
  const [renderError, setRenderError] = useState(false)
  const [size, setSize] = useState<CanvasSize>({ width: 0, height: 0 })
  const document = usePresentationStore((state) => state.document)
  const activeSlideId = usePresentationStore((state) => state.view.activeSlideId)
  const selectedElementId = usePresentationStore((state) => state.view.selectedElementIds[0] ?? null)
  const editingElementId = usePresentationStore((state) => state.view.editingElementId)
  const zoom = usePresentationStore((state) => state.view.zoom)
  const pan = usePresentationStore((state) => state.view.pan)
  const transformPreview = usePresentationStore((state) => state.view.transformPreview)
  const guides = usePresentationStore((state) => state.view.guides)
  const activeSlide = document?.slides.find((slide) => slide.id === activeSlideId) ?? document?.slides[0]
  const selectedElement = activeSlide?.elements.find((element) => element.id === selectedElementId)
  const editingElement = activeSlide?.elements.find((element) => element.id === editingElementId)
  const viewport = presentationViewport(size, document?.pageSize ?? { width: 0, height: 0 }, zoom, pan)
  // While a gesture runs, the frame and its handles describe the previewed
  // geometry; the document only changes when the gesture is committed.
  const selectedGeometry = selectedElement ? elementGeometry(selectedElement, transformPreview) : null

  useEffect(() => {
    const host = hostRef.current
    if (!host) return
    const update = () => setSize({ width: host.clientWidth, height: host.clientHeight })
    update()
    const observer = new ResizeObserver(update)
    observer.observe(host)
    return () => observer.disconnect()
  }, [])

  useEffect(() => {
    const host = hostRef.current
    if (!host || stageRef.current) return
    const stage = new Konva.Stage({ container: host, width: Math.max(1, host.clientWidth), height: Math.max(1, host.clientHeight) })
    const layer = new Konva.Layer()
    stage.add(layer)
    stageRef.current = stage
    layerRef.current = layer
    return () => {
      stage.destroy()
      stageRef.current = null
      layerRef.current = null
    }
  }, [])

  useEffect(() => {
    const layer = layerRef.current
    if (!layer || !document || !activeSlide) return
    layer.destroyChildren()
    try {
      const page = renderSlide({ slide: activeSlide, pageSize: document.pageSize, images, listening: true })
      if (editingElementId) {
        // The DOM overlay draws the text being edited; hide the canvas copy.
        for (const child of page.getChildren()) {
          if (child.id() === editingElementId) {
            child.visible(false)
            break
          }
        }
      }
      layer.add(page)
      setRenderError(false)
    } catch {
      // A missing decoded asset must not unmount the whole app: the preview
      // reports the problem and the rest of the editor keeps working.
      setRenderError(true)
    }
    layer.draw()
  }, [activeSlide, document, editingElementId, images])

  useEffect(() => {
    const stage = stageRef.current
    if (!stage || !document) return
    stage.size({ width: Math.max(1, size.width), height: Math.max(1, size.height) })
    stage.scale({ x: viewport.scale, y: viewport.scale })
    stage.position({ x: viewport.x, y: viewport.y })
    stage.batchDraw()
  }, [document, size, viewport.scale, viewport.x, viewport.y])

  // Live gesture feedback on the rendering layer only: the group follows the
  // pointer, and the committed document redraws it at its real geometry. A
  // cancelled gesture puts the node back where the document says it is.
  useEffect(() => {
    const layer = layerRef.current
    const id = transformPreview?.elementId ?? previewedNodeId.current
    if (!layer || !id) return
    const element = activeSlide?.elements.find((candidate) => candidate.id === id)
    const node = layer.findOne(`#${id}`) as Konva.Group | undefined
    if (element && node) {
      const geometry = elementGeometry(element, transformPreview)
      node.setAttrs({
        x: geometry.x,
        y: geometry.y,
        rotation: geometry.rotation,
        // Preview only: the group is scaled so the drag tracks the pointer. The
        // stored element keeps its own size and is re-rendered from it.
        scaleX: geometry.width / element.width,
        scaleY: geometry.height / element.height,
      })
      layer.batchDraw()
    }
    previewedNodeId.current = transformPreview?.elementId ?? null
  }, [transformPreview, activeSlide])

  useEffect(() => {
    const stage = stageRef.current
    if (!stage) return
    const elementIdFor = (target: Konva.Node): string | null => {
      if (target === stage) return null
      const group = target.findAncestor('.presentation-element', true) as Konva.Group | undefined
      return group?.id() || null
    }
    const select = (event: Konva.KonvaEventObject<MouseEvent | TouchEvent>) => {
      const id = elementIdFor(event.target)
      usePresentationStore.getState().selectElements(id ? [id] : [])
    }
    const edit = (event: Konva.KonvaEventObject<MouseEvent | TouchEvent>) => {
      const id = elementIdFor(event.target)
      if (id) usePresentationStore.getState().startTextEdit(id)
    }
    stage.on('click tap', select)
    stage.on('dblclick dbltap', edit)
    return () => {
      stage.off('click tap', select)
      stage.off('dblclick dbltap', edit)
    }
  }, [])

  useEffect(() => {
    const host = hostRef.current
    if (!host) return
    const onWheel = (event: WheelEvent) => {
      if (event.deltaY === 0) return
      event.preventDefault()
      const current = usePresentationStore.getState().view.zoom
      usePresentationStore.getState().setZoom(clampPresentationZoom(current * (event.deltaY < 0 ? 1.1 : 0.9)))
    }
    host.addEventListener('wheel', onWheel, { passive: false })
    return () => host.removeEventListener('wheel', onWheel)
  }, [])

  // Keep focus in the editor when the text overlay closes, but never steal it.
  useEffect(() => {
    const host = hostRef.current
    if (editingElementId) {
      wasEditing.current = true
      return
    }
    if (!wasEditing.current || !host) return
    wasEditing.current = false
    // `document` in this scope is the presentation document, so reach for the DOM one explicitly.
    if (window.document.activeElement === null || window.document.activeElement === window.document.body) host.focus()
  }, [editingElementId])

  const captureTarget = () => hostRef.current?.querySelector<HTMLElement>('.konvajs-content') ?? hostRef.current

  const endPan = (pointerId: number) => {
    const gesture = panGesture.current
    if (gesture?.pointerId !== pointerId) return
    panGesture.current = null
    setPanning(false)
    if (gesture.capture?.hasPointerCapture(pointerId)) {
      try { gesture.capture.releasePointerCapture(pointerId) } catch { /* Pointer capture already ended. */ }
    }
  }

  /** One pointer position in document units, through the shared viewport mapping. */
  const pointFromClient = (clientX: number, clientY: number): ViewPoint | null => {
    const host = hostRef.current
    if (!host) return null
    const rect = host.getBoundingClientRect()
    return documentPointFromView({ x: clientX - rect.left, y: clientY - rect.top }, viewport)
  }

  /** The visible element under the pointer, or null over the slide background. */
  const elementAtPointer = (clientX: number, clientY: number): Element | null => {
    const stage = stageRef.current
    const host = hostRef.current
    if (!stage || !host || !activeSlide) return null
    const rect = host.getBoundingClientRect()
    const hit = stage.getIntersection({ x: clientX - rect.left, y: clientY - rect.top })
    if (!hit) return null
    const id = (hit.findAncestor('.presentation-element', true) as Konva.Group | undefined)?.id()
    return id ? activeSlide.elements.find((element) => element.id === id) ?? null : null
  }

  const beginTransform = (element: Element, kind: TransformGesture['kind'], handle: ResizeHandle | null, event: ReactPointerEvent<HTMLElement>) => {
    const origin = pointFromClient(event.clientX, event.clientY)
    if (!origin) return
    const start = elementGeometry(element, null)
    // Capture on the Konva container for every transform gesture, so move/up
    // arrive through the same host handlers as panning.
    const capture = captureTarget()
    transformGesture.current = {
      kind,
      pointerId: event.pointerId,
      elementId: element.id,
      handle,
      origin,
      start,
      current: null,
      // Rotation measures the pointer angle around the element's visual centre.
      pointerAngle: kind === 'rotate' ? rotationFromPoint(elementWorldCenter(start), origin) : 0,
      rotationTurn: 0,
      capture,
    }
    try { capture?.setPointerCapture(event.pointerId) } catch { /* Window-level pointer events still reach the host. */ }
  }

  /**
   * The candidate geometry for one pointer position. Move and resize measure
   * from the gesture's start; rotation walks the pointer angle step by step,
   * updating the gesture, so a continuous turn accumulates instead of jumping at
   * the ±180° branch cut.
   */
  const previewGeometry = (gesture: TransformGesture, point: ViewPoint): TransformGeometry => {
    if (gesture.kind === 'move') return moveTransform(gesture.start, { x: point.x - gesture.origin.x, y: point.y - gesture.origin.y })
    if (gesture.kind === 'resize') return resizeTransform(gesture.start, gesture.handle!, point)
    const step = nextRotationStep(gesture.pointerAngle, rotationFromPoint(elementWorldCenter(gesture.start), point), gesture.rotationTurn)
    gesture.pointerAngle = step.angle
    gesture.rotationTurn = step.accumulated
    return rotateTransform(gesture.start, step.accumulated)
  }

  /** Applies pointer movement to the live gesture; returns whether one is running. */
  const applyGestureMove = (event: ReactPointerEvent<HTMLDivElement>): boolean => {
    const gesture = transformGesture.current
    if (!gesture || gesture.pointerId !== event.pointerId) return false
    // A mouse drag whose button was released outside the window must not keep
    // transforming on plain hover movement.
    if (event.pointerType === 'mouse' && (event.buttons & 1) === 0) {
      endTransform(event.pointerId, false)
      return true
    }
    const point = pointFromClient(event.clientX, event.clientY)
    if (!point) return true
    let current = previewGeometry(gesture, point)
    let nextGuides: AlignmentGuide[] = []
    // Move gestures snap to other visible elements and the page axes, and show
    // the matched lines. Resize and rotate keep exact pointer geometry.
    if (gesture.kind === 'move' && activeSlide && document) {
      const others = activeSlide.elements
        .filter((element) => element.id !== gesture.elementId && element.visible)
        .map((element) => elementGeometry(element, null))
      const snapped = snapToAlignment(current, others, document.pageSize)
      current = { ...current, x: snapped.x, y: snapped.y }
      nextGuides = snapped.guides
    }
    gesture.current = current
    const store = usePresentationStore.getState()
    store.setTransformPreview({ elementId: gesture.elementId, ...current })
    store.setGuides(nextGuides)
    return true
  }

  const endTransform = (pointerId: number, commit: boolean) => {
    const gesture = transformGesture.current
    if (gesture?.pointerId !== pointerId) return
    transformGesture.current = null
    if (gesture.capture?.hasPointerCapture(pointerId)) {
      try { gesture.capture.releasePointerCapture(pointerId) } catch { /* Pointer capture already ended. */ }
    }
    const store = usePresentationStore.getState()
    // A click without movement leaves no undo entry and no revision behind.
    if (commit && gesture.current) store.commitTransform(gesture.elementId, gesture.current)
    else if (gesture.current) store.setTransformPreview(null)
    store.setGuides([])
  }

  if (!document || !activeSlide) return null

  return (
    <section className="presentation-canvas-panel" aria-label="Slide canvas">
      <PresentationCanvasControls />
      <div
        ref={hostRef}
        className={`presentation-canvas${panning ? ' is-panning' : ''}`}
        data-testid="presentation-canvas"
        data-document-width={document.pageSize.width}
        data-document-height={document.pageSize.height}
        data-view-zoom={zoom}
        data-view-pan-x={pan.x}
        data-view-pan-y={pan.y}
        data-selected-element={selectedElementId ?? ''}
        data-editing-element={editingElementId ?? ''}
        tabIndex={-1}
        onPointerDown={(event) => {
          if (event.button !== 0) return
          const element = elementAtPointer(event.clientX, event.clientY)
          if (element) {
            usePresentationStore.getState().selectElements([element.id])
            // A locked element stays selectable so its properties are reachable,
            // but no gesture may move, resize, or rotate it.
            if (!element.locked) beginTransform(element, 'move', null, event)
            return
          }
          // Capture on the Konva container so Konva still sees pointerdown/up and can
          // report click/dblclick for element selection.
          const capture = captureTarget()
          panGesture.current = { pointerId: event.pointerId, x: event.clientX, y: event.clientY, capture }
          setPanning(true)
          try { capture?.setPointerCapture(event.pointerId) } catch { /* Window-level pointer events still update the view. */ }
        }}
        onPointerMove={(event) => {
          if (applyGestureMove(event)) return
          const gesture = panGesture.current
          if (!gesture || gesture.pointerId !== event.pointerId) return
          // A mouse drag whose button was released outside the window must not
          // keep panning on plain hover movement.
          if (event.pointerType === 'mouse' && (event.buttons & 1) === 0) {
            endPan(event.pointerId)
            return
          }
          const dx = event.clientX - gesture.x
          const dy = event.clientY - gesture.y
          gesture.x = event.clientX
          gesture.y = event.clientY
          const currentPan = usePresentationStore.getState().view.pan
          usePresentationStore.getState().setPan({ x: currentPan.x + dx, y: currentPan.y + dy })
        }}
        onPointerUp={(event) => {
          endTransform(event.pointerId, true)
          endPan(event.pointerId)
        }}
        onPointerCancel={(event) => {
          endTransform(event.pointerId, false)
          endPan(event.pointerId)
        }}
      />
      {selectedElement && selectedGeometry && !editingElement ? (
        <PresentationSelectionFrame
          geometry={selectedGeometry}
          viewport={viewport}
          locked={selectedElement.locked}
          onGestureStart={(kind, handle, event) => {
            // The handle gesture must not also start a pan or a move on the host.
            event.preventDefault()
            event.stopPropagation()
            beginTransform(selectedElement, kind, handle, event)
          }}
        />
      ) : null}
      {editingElement?.kind === 'text' ? (
        <TextEditOverlay element={editingElement} scale={viewport.scale} offsetX={viewport.x} offsetY={viewport.y} theme={document.theme} />
      ) : null}
      {renderError ? <p className="presentation-canvas-error" role="alert">Some artwork on this slide could not be drawn. Your saved presentation is unchanged.</p> : null}
      {activeSlide.elements.length === 0 && !renderError ? <p className="presentation-blank-slide" aria-hidden="true">Blank slide</p> : null}
      {guides.map((guide, index) => (
        <div
          key={`${guide.axis}-${guide.position}-${index}`}
          className={`presentation-guide is-${guide.axis}`}
          data-testid={`presentation-guide-${guide.axis}`}
          aria-hidden="true"
          style={guide.axis === 'x'
            ? { left: viewport.x + guide.position * viewport.scale, top: viewport.y, height: document.pageSize.height * viewport.scale }
            : { top: viewport.y + guide.position * viewport.scale, left: viewport.x, width: document.pageSize.width * viewport.scale }}
        />
      ))}
    </section>
  )
}
