// src/lib/components/presentation/TextFormatToolbar.svelte
<script>
	import {
		AlignCenter,
		AlignJustify,
		AlignLeft,
		AlignRight,
		Bold,
		IndentDecrease,
		IndentIncrease,
		Italic,
		Link2,
		Link2Off,
		List,
		ListOrdered
	} from 'lucide-svelte';
	import { PRESENTATION_FONT_FAMILIES } from '$lib/presentations/rendering/fonts';

	/**
	 * `svelte2tsx` infers a `$state.raw(null)` variable from its initialiser, so the
	 * precise type has to be asserted on the argument rather than declared above.
	 * @typedef {import('$lib/presentations/editor/textFormat').TextFormatState} TextFormatState
	 * @typedef {import('$lib/presentations/editor/textFormat').ParagraphFormatState} ParagraphFormatState
	 */

	/**
	 * Text formatting toolbar (P26/P27). It reads and writes the live editing
	 * session through the controller `TextEditOverlay` registers, so it never
	 * reaches into the DOM field itself. Buttons keep the field focused; selects,
	 * the color control and the link field may take focus, and the overlay
	 * restores the cached selection for them.
	 *
	 * @type {{
	 *   session: import('$lib/presentations/editor/textEditSession.svelte').TextEditSession
	 * }}
	 */
	let { session } = $props();

	const FONT_SIZES = [12, 14, 16, 18, 20, 24, 28, 32, 40, 48, 56, 64, 80, 96];
	const LINE_HEIGHTS = [1, 1.15, 1.5, 2];
	const ALIGNMENTS = /** @type {const} */ (['left', 'center', 'right', 'justify']);
	const ALIGN_ICONS = {
		left: AlignLeft,
		center: AlignCenter,
		right: AlignRight,
		justify: AlignJustify
	};

	let format = $state.raw(/** @type {TextFormatState | null} */ (null));
	let paragraph = $state.raw(/** @type {ParagraphFormatState | null} */ (null));
	let lineHeight = $state(1);
	let linkValue = $state('');
	/** @type {string | null} */
	let linkError = $state(null);

	function refresh() {
		const active = session.format();
		if (!active) {
			format = null;
			paragraph = null;
			return;
		}
		format = active.read();
		paragraph = active.readParagraph();
		lineHeight = active.lineHeight();
	}

	// Caret and selection moves are not reactive state, so they arrive as DOM
	// events; the field itself is owned by the overlay.
	$effect(() => {
		const onSelectionChange = () => refresh();
		document.addEventListener('selectionchange', onSelectionChange);
		return () => document.removeEventListener('selectionchange', onSelectionChange);
	});

	$effect(() => {
		// `refresh` reads the session's controller, which is reactive state: the
		// toolbar follows the overlay as it registers the controller when a field
		// opens and releases it when the field closes.
		refresh();
	});

	/** @param {import('$lib/presentations/editor/textFormat').RunStylePatch} patch */
	function apply(patch) {
		const active = session.format();
		if (!active) return;
		active.apply(patch);
		refresh();
	}

	/** @param {import('$lib/presentations/editor/textFormat').ParagraphStylePatch} patch */
	function applyParagraph(patch) {
		const active = session.format();
		if (!active) return;
		active.applyParagraph(patch);
		refresh();
	}

	/** @param {SubmitEvent} event */
	function submitLink(event) {
		event.preventDefault();
		const active = session.format();
		if (!active) return;
		const value = linkValue.trim();
		if (!value) {
			linkError = 'Enter a link address, or use Remove link.';
			return;
		}
		const result = active.applyLink(value);
		if (!result.ok) {
			linkError = result.message;
			return;
		}
		linkError = null;
		linkValue = '';
		refresh();
	}

	function removeLink() {
		const active = session.format();
		if (!active) return;
		active.applyLink(null);
		linkError = null;
		linkValue = '';
		refresh();
	}

	const knownFont = $derived(
		format?.fontId != null &&
			PRESENTATION_FONT_FAMILIES.some((family) => family.id === format?.fontId)
	);
	const knownSize = $derived(format?.size != null && FONT_SIZES.includes(format.size));
	const knownLineHeight = $derived(LINE_HEIGHTS.includes(lineHeight));
	const level = $derived(paragraph?.bulletLevel ?? 0);
</script>

{#if format && paragraph}
	<div
		class="presentation-text-toolbar"
		data-text-toolbar
		role="toolbar"
		aria-label="Text formatting"
	>
		<div class="presentation-text-toolbar-group" role="group" aria-label="Character">
			<button
				type="button"
				class="button icon"
				aria-label="Bold"
				aria-pressed={format.bold}
				title="Bold"
				onmousedown={(event) => event.preventDefault()}
				onclick={() => apply({ bold: !format?.bold })}><Bold size={16} aria-hidden="true" /></button
			>
			<button
				type="button"
				class="button icon"
				aria-label="Italic"
				aria-pressed={format.italic}
				title="Italic"
				onmousedown={(event) => event.preventDefault()}
				onclick={() => apply({ italic: !format?.italic })}
				><Italic size={16} aria-hidden="true" /></button
			>
			<label class="presentation-text-toolbar-field">
				<span class="sr-only">Font family</span>
				<select
					aria-label="Font family"
					value={format.fontId ?? ''}
					onchange={(event) => apply({ fontId: event.currentTarget.value })}
				>
					{#if format.fontId === null}<option value="">Mixed</option>{/if}
					{#if !knownFont && format.fontId !== null}<option value={format.fontId}
							>{format.fontId}</option
						>{/if}
					{#each PRESENTATION_FONT_FAMILIES as family (family.id)}
						<option value={family.id}>{family.displayName}</option>
					{/each}
				</select>
			</label>
			<label class="presentation-text-toolbar-field">
				<span class="sr-only">Font size</span>
				<select
					aria-label="Font size"
					value={format.size ?? ''}
					onchange={(event) => apply({ size: Number(event.currentTarget.value) })}
				>
					{#if format.size === null}<option value="">Mixed</option>{/if}
					{#if !knownSize && format.size !== null}<option value={format.size}>{format.size}</option
						>{/if}
					{#each FONT_SIZES as size (size)}
						<option value={size}>{size}</option>
					{/each}
				</select>
			</label>
			<label class="presentation-text-toolbar-field presentation-text-toolbar-color">
				<span class="sr-only">Text color</span>
				<input
					type="color"
					aria-label="Text color"
					value={format.color ?? '#08152f'}
					oninput={(event) => apply({ color: event.currentTarget.value })}
				/>
			</label>
		</div>

		<div class="presentation-text-toolbar-group" role="group" aria-label="Paragraph">
			{#each ALIGNMENTS as alignment (alignment)}
				{@const Icon = ALIGN_ICONS[alignment]}
				<button
					type="button"
					class="button icon"
					aria-label="Align {alignment}"
					aria-pressed={paragraph.alignment === alignment}
					title="Align {alignment}"
					onmousedown={(event) => event.preventDefault()}
					onclick={() => applyParagraph({ alignment })}
					><Icon size={16} aria-hidden="true" /></button
				>
			{/each}
			<button
				type="button"
				class="button icon"
				aria-label="Bulleted list"
				aria-pressed={paragraph.bullet === 'bullet'}
				title="Bulleted list"
				onmousedown={(event) => event.preventDefault()}
				onclick={() =>
					applyParagraph({ bullet: paragraph?.bullet === 'bullet' ? 'none' : 'bullet' })}
				><List size={16} aria-hidden="true" /></button
			>
			<button
				type="button"
				class="button icon"
				aria-label="Numbered list"
				aria-pressed={paragraph.bullet === 'number'}
				title="Numbered list"
				onmousedown={(event) => event.preventDefault()}
				onclick={() =>
					applyParagraph({ bullet: paragraph?.bullet === 'number' ? 'none' : 'number' })}
				><ListOrdered size={16} aria-hidden="true" /></button
			>
			<button
				type="button"
				class="button icon"
				aria-label="Decrease indent"
				title="Decrease indent"
				disabled={paragraph.bullet === 'none' || level === 0}
				onmousedown={(event) => event.preventDefault()}
				onclick={() =>
					applyParagraph({ bulletLevel: /** @type {0 | 1 | 2} */ (Math.max(0, level - 1)) })}
				><IndentDecrease size={16} aria-hidden="true" /></button
			>
			<button
				type="button"
				class="button icon"
				aria-label="Increase indent"
				title="Increase indent"
				disabled={level === 2}
				onmousedown={(event) => event.preventDefault()}
				onclick={() =>
					applyParagraph({
						bullet: paragraph?.bullet === 'none' ? 'bullet' : undefined,
						bulletLevel: /** @type {0 | 1 | 2} */ (Math.min(2, level + 1))
					})}><IndentIncrease size={16} aria-hidden="true" /></button
			>
			<label class="presentation-text-toolbar-field">
				<span class="sr-only">Line spacing</span>
				<select
					aria-label="Line spacing"
					value={lineHeight}
					onchange={(event) => {
						const next = Number(event.currentTarget.value);
						session.format()?.setLineHeight(next);
						lineHeight = next;
					}}
				>
					{#if !knownLineHeight}<option value={lineHeight}>{lineHeight}</option>{/if}
					{#each LINE_HEIGHTS as value (value)}
						<option {value}>{value}</option>
					{/each}
				</select>
			</label>
		</div>

		<form
			class="presentation-text-toolbar-group presentation-text-toolbar-link"
			onsubmit={submitLink}
		>
			<label class="presentation-text-toolbar-field">
				<span class="sr-only">Link URL</span>
				<input
					type="text"
					inputmode="url"
					aria-label="Link URL"
					placeholder="https://…"
					value={linkValue}
					oninput={(event) => {
						linkValue = event.currentTarget.value;
						linkError = null;
					}}
				/>
			</label>
			<button
				type="submit"
				class="button"
				title="Add link"
				onmousedown={(event) => event.preventDefault()}
				><Link2 size={16} aria-hidden="true" /> Add link</button
			>
			{#if format.link}
				<button
					type="button"
					class="button icon"
					aria-label="Remove link"
					title="Remove link"
					onmousedown={(event) => event.preventDefault()}
					onclick={removeLink}><Link2Off size={16} aria-hidden="true" /></button
				>
			{/if}
			{#if linkError}<p class="presentation-text-toolbar-error" role="alert">{linkError}</p>{/if}
		</form>
	</div>
{/if}

// src/features/presentations/editor/TextFormatToolbar.tsx
/**
 * Text formatting toolbar (P26/P27). It reads and writes the live editing
 * session through the controller `TextEditOverlay` registers, so it never
 * reaches into the DOM field itself. Buttons keep the field focused; selects,
 * the color control and the link field may take focus, and the overlay restores
 * the cached selection for them.
 */

import { AlignCenter, AlignJustify, AlignLeft, AlignRight, Bold, IndentDecrease, IndentIncrease, Italic, Link2, Link2Off, List, ListOrdered } from 'lucide-react'
import { useCallback, useEffect, useState, useSyncExternalStore, type FormEvent } from 'react'
import { Button } from '@/components/ui/button'
import { PRESENTATION_FONT_FAMILIES } from '../rendering/fonts'
import { activeTextEditFormat, subscribeActiveTextEditFormat } from './textEditSession'
import type { ParagraphFormatState, ParagraphStylePatch, RunStylePatch, TextFormatState } from './textFormat'

const FONT_SIZES = [12, 14, 16, 18, 20, 24, 28, 32, 40, 48, 56, 64, 80, 96]
const LINE_HEIGHTS = [1, 1.15, 1.5, 2]

export function TextFormatToolbar() {
  const controller = useSyncExternalStore(subscribeActiveTextEditFormat, activeTextEditFormat, () => null)
  const [format, setFormat] = useState<TextFormatState | null>(null)
  const [paragraph, setParagraph] = useState<ParagraphFormatState | null>(null)
  const [lineHeight, setLineHeight] = useState(1)
  const [linkValue, setLinkValue] = useState('')
  const [linkError, setLinkError] = useState<string | null>(null)

  const refresh = useCallback(() => {
    const active = activeTextEditFormat()
    if (!active) {
      setFormat(null)
      setParagraph(null)
      return
    }
    setFormat(active.read())
    setParagraph(active.readParagraph())
    setLineHeight(active.lineHeight())
  }, [])

  useEffect(() => {
    if (!controller) {
      setFormat(null)
      setParagraph(null)
      return
    }
    refresh()
    document.addEventListener('selectionchange', refresh)
    return () => document.removeEventListener('selectionchange', refresh)
  }, [controller, refresh])

  if (!controller || !format || !paragraph) return null

  const apply = (patch: RunStylePatch) => {
    controller.apply(patch)
    refresh()
  }

  const applyParagraph = (patch: ParagraphStylePatch) => {
    controller.applyParagraph(patch)
    refresh()
  }

  const submitLink = (event: FormEvent) => {
    event.preventDefault()
    const value = linkValue.trim()
    if (!value) {
      setLinkError('Enter a link address, or use Remove link.')
      return
    }
    const result = controller.applyLink(value)
    if (!result.ok) {
      setLinkError(result.message)
      return
    }
    setLinkError(null)
    setLinkValue('')
    refresh()
  }

  const removeLink = () => {
    controller.applyLink(null)
    setLinkError(null)
    setLinkValue('')
    refresh()
  }

  const knownFont = format.fontId !== null && PRESENTATION_FONT_FAMILIES.some((family) => family.id === format.fontId)
  const knownSize = format.size !== null && FONT_SIZES.includes(format.size)
  const level = paragraph.bulletLevel ?? 0
  const knownLineHeight = LINE_HEIGHTS.includes(lineHeight)

  return (
    <div className="presentation-text-toolbar" data-text-toolbar role="toolbar" aria-label="Text formatting">
      <div className="presentation-text-toolbar-group" role="group" aria-label="Character">
        <Button
          className="icon"
          aria-label="Bold"
          aria-pressed={format.bold}
          title="Bold"
          onMouseDown={(event) => event.preventDefault()}
          onClick={() => apply({ bold: !format.bold })}
        >
          <Bold size={16} aria-hidden="true" />
        </Button>
        <Button
          className="icon"
          aria-label="Italic"
          aria-pressed={format.italic}
          title="Italic"
          onMouseDown={(event) => event.preventDefault()}
          onClick={() => apply({ italic: !format.italic })}
        >
          <Italic size={16} aria-hidden="true" />
        </Button>
        <label className="presentation-text-toolbar-field">
          <span className="sr-only">Font family</span>
          <select aria-label="Font family" value={format.fontId ?? ''} onChange={(event) => apply({ fontId: event.target.value })}>
            {format.fontId === null ? <option value="">Mixed</option> : null}
            {!knownFont && format.fontId !== null ? <option value={format.fontId}>{format.fontId}</option> : null}
            {PRESENTATION_FONT_FAMILIES.map((family) => (
              <option key={family.id} value={family.id}>{family.displayName}</option>
            ))}
          </select>
        </label>
        <label className="presentation-text-toolbar-field">
          <span className="sr-only">Font size</span>
          <select aria-label="Font size" value={format.size ?? ''} onChange={(event) => apply({ size: Number(event.target.value) })}>
            {format.size === null ? <option value="">Mixed</option> : null}
            {!knownSize && format.size !== null ? <option value={format.size}>{format.size}</option> : null}
            {FONT_SIZES.map((size) => (
              <option key={size} value={size}>{size}</option>
            ))}
          </select>
        </label>
        <label className="presentation-text-toolbar-field presentation-text-toolbar-color">
          <span className="sr-only">Text color</span>
          <input type="color" aria-label="Text color" value={format.color ?? '#08152f'} onChange={(event) => apply({ color: event.target.value })} />
        </label>
      </div>

      <div className="presentation-text-toolbar-group" role="group" aria-label="Paragraph">
        {(['left', 'center', 'right', 'justify'] as const).map((alignment) => {
          const Icon = alignment === 'left' ? AlignLeft : alignment === 'center' ? AlignCenter : alignment === 'right' ? AlignRight : AlignJustify
          return (
            <Button
              key={alignment}
              className="icon"
              aria-label={`Align ${alignment}`}
              aria-pressed={paragraph.alignment === alignment}
              title={`Align ${alignment}`}
              onMouseDown={(event) => event.preventDefault()}
              onClick={() => applyParagraph({ alignment })}
            >
              <Icon size={16} aria-hidden="true" />
            </Button>
          )
        })}
        <Button
          className="icon"
          aria-label="Bulleted list"
          aria-pressed={paragraph.bullet === 'bullet'}
          title="Bulleted list"
          onMouseDown={(event) => event.preventDefault()}
          onClick={() => applyParagraph({ bullet: paragraph.bullet === 'bullet' ? 'none' : 'bullet' })}
        >
          <List size={16} aria-hidden="true" />
        </Button>
        <Button
          className="icon"
          aria-label="Numbered list"
          aria-pressed={paragraph.bullet === 'number'}
          title="Numbered list"
          onMouseDown={(event) => event.preventDefault()}
          onClick={() => applyParagraph({ bullet: paragraph.bullet === 'number' ? 'none' : 'number' })}
        >
          <ListOrdered size={16} aria-hidden="true" />
        </Button>
        <Button
          className="icon"
          aria-label="Decrease indent"
          title="Decrease indent"
          disabled={paragraph.bullet === 'none' || level === 0}
          onMouseDown={(event) => event.preventDefault()}
          onClick={() => applyParagraph({ bulletLevel: Math.max(0, level - 1) as 0 | 1 | 2 })}
        >
          <IndentDecrease size={16} aria-hidden="true" />
        </Button>
        <Button
          className="icon"
          aria-label="Increase indent"
          title="Increase indent"
          disabled={level === 2}
          onMouseDown={(event) => event.preventDefault()}
          onClick={() => applyParagraph({ bullet: paragraph.bullet === 'none' ? 'bullet' : undefined, bulletLevel: Math.min(2, level + 1) as 0 | 1 | 2 })}
        >
          <IndentIncrease size={16} aria-hidden="true" />
        </Button>
        <label className="presentation-text-toolbar-field">
          <span className="sr-only">Line spacing</span>
          <select aria-label="Line spacing" value={lineHeight} onChange={(event) => {
            const next = Number(event.target.value)
            controller.setLineHeight(next)
            setLineHeight(next)
          }}>
            {!knownLineHeight ? <option value={lineHeight}>{lineHeight}</option> : null}
            {LINE_HEIGHTS.map((value) => (
              <option key={value} value={value}>{value}</option>
            ))}
          </select>
        </label>
      </div>

      <form className="presentation-text-toolbar-group presentation-text-toolbar-link" onSubmit={submitLink}>
        <label className="presentation-text-toolbar-field">
          <span className="sr-only">Link URL</span>
          <input
            type="text"
            inputMode="url"
            aria-label="Link URL"
            placeholder="https://…"
            value={linkValue}
            onChange={(event) => {
              setLinkValue(event.target.value)
              setLinkError(null)
            }}
          />
        </label>
        <Button type="submit" title="Add link" onMouseDown={(event) => event.preventDefault()}>
          <Link2 size={16} aria-hidden="true" /> Add link
        </Button>
        {format.link ? (
          <Button type="button" aria-label="Remove link" title="Remove link" onMouseDown={(event) => event.preventDefault()} onClick={removeLink}>
            <Link2Off size={16} aria-hidden="true" />
          </Button>
        ) : null}
        {linkError ? <p className="presentation-text-toolbar-error" role="alert">{linkError}</p> : null}
      </form>
    </div>
  )
}
