// src/lib/components/PresentationThumb.svelte
<script>
	import {
		acquirePresentationThumbnail,
		presentationThumbnailKey,
		releasePresentationThumbnail
	} from '$lib/presentations/library/presentationThumbnails';

	/** @type {{
	 *   repository: import('$lib/presentations/persistence/repository').PresentationRepository,
	 *   documentId: string,
	 *   revision: number,
	 *   source?: import('$lib/presentations/library/presentationThumbnails').PresentationThumbnailSource
	 * }} */
	let { repository, documentId, revision, source = undefined } = $props();

	let url = $state(/** @type {string | null} */ (null));

	/** @type {import('svelte/attachments').Attachment<HTMLElement>} */
	const loadWhenVisible = (node) => {
		const key = presentationThumbnailKey(documentId, revision);
		let live = true;
		/** @type {IntersectionObserver | undefined} */
		let observer;

		const load = async () => {
			observer?.disconnect();
			const thumbnail = await acquirePresentationThumbnail(
				{ repository, documentId, revision },
				source
			);
			if (live) url = thumbnail?.url ?? null;
		};

		url = null;
		if (typeof IntersectionObserver === 'undefined') {
			void load();
		} else {
			observer = new IntersectionObserver(
				(entries) => {
					if (entries.some((entry) => entry.isIntersecting)) void load();
				},
				{ rootMargin: '240px' }
			);
			observer.observe(node);
		}

		return () => {
			live = false;
			observer?.disconnect();
			releasePresentationThumbnail(key);
		};
	};
</script>

<span
	class="presentation-card-thumb [position:absolute] [inset:0] [z-index:2]"
	{@attach loadWhenVisible}
>
	{#if url}
		<img data-testid="presentation-card-thumb" src={url} alt="" width="480" height="270" />
	{/if}
</span>

<style>
	/* Migrated from the former global layout stylesheet; scoped to this owner. */
	/* The real slide render sits over the paper preview (z-index 1) and its tape: absolute and opaque, so
   it can neither move the card's layout nor leave the paper showing through it. */
	.presentation-card-thumb img {
		display: block;
		width: 100%;
		height: 100%;
		object-fit: cover;
	}
</style>

// src/features/presentations/library/PresentationThumb.tsx
import { useEffect, useRef, useState } from 'react'
import { usePresentationRepository } from '@/app/presentationRepositoryContext'
import {
  PRESENTATION_THUMBNAIL_HEIGHT,
  PRESENTATION_THUMBNAIL_WIDTH,
  acquirePresentationThumbnail,
  presentationThumbnailKey,
  releasePresentationThumbnail,
  type PresentationThumbnailSource,
} from './presentationThumbnails'

/**
 * The real first-slide render of one library card, drawn over the decorative
 * paper preview. The card keeps its paper until a raster exists, so loading and
 * every failure look exactly like the card did before thumbnails existed.
 *
 * The slot is an empty box that never affects layout, and the whole preview is
 * aria-hidden: the card's name and link come from the title text, not from here.
 */
export function PresentationThumb({
  documentId,
  revision,
  source,
}: {
  documentId: string
  revision: number
  /** Test seam; the library uses the stored-slide source. */
  source?: PresentationThumbnailSource
}) {
  const repository = usePresentationRepository()
  const slot = useRef<HTMLSpanElement>(null)
  const key = presentationThumbnailKey(documentId, revision)
  const [nearViewport, setNearViewport] = useState(false)
  const [url, setUrl] = useState<string | null>(null)

  useEffect(() => {
    const element = slot.current
    if (!element) return
    // jsdom has no IntersectionObserver; there every card counts as on screen.
    if (typeof IntersectionObserver === 'undefined') {
      setNearViewport(true)
      return
    }
    const observer = new IntersectionObserver(
      (entries) => {
        if (!entries.some((entry) => entry.isIntersecting)) return
        setNearViewport(true)
        observer.disconnect()
      },
      // A little ahead of the fold, so a card is drawn before it is scrolled to.
      { rootMargin: '200px' },
    )
    observer.observe(element)
    return () => observer.disconnect()
  }, [])

  useEffect(() => {
    if (!nearViewport) return
    let live = true
    setUrl(null)
    void acquirePresentationThumbnail({ repository, documentId, revision }, source).then((thumbnail) => {
      if (live && thumbnail) setUrl(thumbnail.url)
    })
    return () => {
      live = false
      releasePresentationThumbnail(key)
    }
  }, [nearViewport, repository, documentId, revision, key, source])

  return (
    <span ref={slot} className="presentation-card-thumb">
      {url ? (
        <img
          data-testid="presentation-card-thumb"
          src={url}
          alt=""
          width={PRESENTATION_THUMBNAIL_WIDTH}
          height={PRESENTATION_THUMBNAIL_HEIGHT}
        />
      ) : null}
    </span>
  )
}

export default PresentationThumb
