// src/features/editor/ProjectThumb.tsx
import { useEffect, useState } from 'react'
import type { ProjectDocument } from '../../types/domain'
import type { StickerLabRepository } from '../../lib/persistence/repository'
import { acquireProjectThumbnail } from './projectThumbnails'

export function ProjectThumb({ project, repo }: { project: ProjectDocument; repo: StickerLabRepository }) {
  const [url, setUrl] = useState<string | null>(null)
  const [failed, setFailed] = useState(false)
  useEffect(() => {
    let live = true
    void (async () => {
      try {
        if (import.meta.env.MODE === 'test') return
        // The thumbnail cache owns the object URL; this component must not revoke it.
        const thumbnail = await acquireProjectThumbnail({ repository: repo, project })
        if (!live) return
        if (thumbnail) setUrl(thumbnail)
        else setFailed(true)
      } catch {
        if (live) { setUrl(null); setFailed(true) }
      }
    })()
    return () => {
      live = false
    }
  }, [project, repo])
  return (
    <div className="project-thumb" aria-hidden="true">
      {url ? <img src={url} alt="" /> : <span className="project-preview-placeholder">{project.layers.length === 0 ? 'Blank canvas' : failed ? 'Preview unavailable' : 'Loading preview…'}</span>}
    </div>
  )
}

// src/lib/components/ProjectThumb.svelte
<script>
	/**
	 * Project card preview. The thumbnail cache owns the object URL, so this
	 * component never revokes it; a failed or pending render falls back to the
	 * source's honest placeholder copy.
	 */
	import { acquireProjectThumbnail } from '$lib/editor/projectThumbnails';

	/** @type {{ project: import('$lib/domain/domain').ProjectDocument, repository: import('$lib/persistence/repository').StickerLabRepository }} */
	let { project, repository } = $props();

	let url = $state(/** @type {string | null} */ (null));
	let failed = $state(false);

	$effect(() => {
		const current = project;
		const repo = repository;
		let live = true;
		void (async () => {
			if (import.meta.env.MODE === 'test') return;
			try {
				const thumbnail = await acquireProjectThumbnail({ repository: repo, project: current });
				if (!live) return;
				if (thumbnail) url = thumbnail;
				else failed = true;
			} catch {
				if (!live) return;
				url = null;
				failed = true;
			}
		})();
		return () => {
			live = false;
		};
	});
</script>

<div class="project-thumb" aria-hidden="true">
	{#if url}
		<img src={url} alt="" />
	{:else}
		<span class="project-preview-placeholder"
			>{project.layers.length === 0
				? 'Blank canvas'
				: failed
					? 'Preview unavailable'
					: 'Loading preview…'}</span
		>
	{/if}
</div>
